spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/cldong?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true

