spring:
  datasource: #db설정
    url: jdbc:mariadb://localhost:3307/cldong?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  devtools: #정적 리소스 서버 재실행 없이 리로드
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

  jpa: #jpa 설정
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true


